### ISSUE TITLE
Provide AlphaMissense as a prediction score

### ISSUE THREAD

**Issue by xiamaz** [varfish-org/varfish-server#1138]
A recent paper by Jun Cheng et al has published a missense prediction model using AlphaFold. The trained model has not been made public, but AA substitution predictions for all missense variants in hg19 and hg38 have been provided publicly: https://console.cloud.google.com/storage/browser/dm_alphamissense;tab=objects?pli=1&prefix=&forceOnObjectsSortingFiltering=false

Jun Cheng et al. ,Accurate proteome-wide missense variant effect prediction with AlphaMissense.Science0,eadg7492DOI:[10.1126/science.adg7492](https://doi.org/10.1126/science.adg7492)

**Comment by holtgrewe** [comment]
Subsumed in #1300
