### ISSUE TITLE
[vueapp] [smallvariants] Results table loses sorting configuration after returning from variant modal

### ISSUE THREAD

**Issue by xiamaz** [varfish-org/varfish-server#1211]
Currently when a user has sorted the table by some column e.g. CADD-Score, clicks a variant to view detail information and returns to the result table, table sortings are lost.

Expected behavior: Table sorting should be retained after closing variant modal.

**Comment by stolpeo** [comment]
Closed by #1212

**Comment by xiamaz** [comment]
This bug has reappeared. @stolpeo Could you check?

**Comment by stolpeo** [comment]
lost after SPA branch merge

**Comment by stolpeo** [comment]
Doesn't seem to be an issue anymore. Closing.
