### ISSUE TITLE
Read env variables for LDAP over TLS

### ISSUE THREAD

**Issue by messersc** [varfish-org/varfish-server#1245]
Add functionality to read some environment vars to enable LDAP over TLS, specifically:

```
AUTH_LDAP_START_TLS
AUTH_LDAP_CA_CERT_FILE
```

Will make a PR.

**Comment by holtgrewe** [comment]
@messersc what is the status here? done?

**Comment by holtgrewe** [comment]
Deployed on internal instance already. Closing.
