### ISSUE TITLE
Keep table position after viewing variant details and going back to the variant table

### ISSUE THREAD

**Issue by flokraft85** [varfish-org/varfish-server#1273]
Issue: Feature request

In previous versions of VarFish the additional information for a variant was shown directly in the variant table, by clicking on the specific variant. Due to the lager amount of information, this is change, so you are redirected to a new page, by clicking on a variant to see all the additional information. However, using the "back button" from this additional variant information page back to the variant table, leads you directly to the head of the table. This behavior could be annoying, when you evaluation variants from the list, which are not among the first ten variants you can see directly from this view. So, you have to scroll down again and again and again, for every variant you click on, to see the additional information.

It would be great, if the "back button" brings you back to exactly the same position in the table, you view before. Or if this is not possible, at least to a position, where the variant you clicked on, is in top of the table.

Best,
Florian

**Comment by holtgrewe** [comment]
Should not be too hard, need to store y position and restore it.
