### ISSUE TITLE
Misleading "no available data" message on empty result sets

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#1275]
**Describe the bug**
When no sequence variant is found, the data table displays "no available data". This is misleading for users.

**To Reproduce**
1. Filter any case so no variant is returned (e.g., try to use a conserved gene in the gene panel)
2. Filter and see message.

**Expected behavior**
Rather display "The result set was empty. Try relaxing your filter criteria."

**Screenshots**
![image](https://github.com/bihealth/varfish-server/assets/521780/0966e232-307a-4be4-ae6a-d7834b512629)

**Additional context**
We need to ensure the behaviour is also changed for structural variants.

**Comment by stolpeo** [comment]
#1310
