### ISSUE TITLE
Synchronize annotator and server Clinvar databases

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#13]
**Is your feature request related to a problem? Please describe.**
Currently there are discrepancies between Clinvar database content of the VarFish server and annotator.

**Describe the solution you'd like**
They should be synchronized and we need to create processes of how to keep them in sync.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by your-highness** [comment]
joining in
