### ISSUE TITLE
Variant icons leads to the wrong postion on the variant details page

### ISSUE THREAD

**Issue by flokraft85** [varfish-org/varfish-server#1315]
**Describe the bug**
When clicking or the first time on the variant icon for flags, comments and ACMG, the links leads to the top of the variant details page and not to the specific position for flags, comments or ACMG. After going back from the variant detail page to the variant filter page an clicking agian on one of these icons, the links leads now to the specific postion. This is the case for every variant. So the first time clicking on an icon the linkt leads to the top of the variant details page. Going back to the variant filter page and clicking again leads to the specific postion on the variant details page.

**To Reproduce**
1. Start on the variant filter page
2. Click on one of the flags, comments or ACMG icons
3. Using the back button, to go back to the variant filter page
4. Click agian on one of the flags, comments or ACMG icons

**Expected behavior**
Clicking on the icons should lead to the specified postion on the variant details page.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox 
 - Version 121
le an clicking agian on one of these icons, the links leads now to the specific postion. This is the case for every variant. So the first time clicking on an icon the linkt leads to the top of the variant details page. Going back to the variant table and clicking again leads to the specific postion on the variant details page.

**To Reproduce**
1. Start on the variant filter page
2. Click on one of the flags, comments or ACMG icons
3. Using the back button, to go back to the variant filter page
4. Click agian on one of the flags, comments or ACMG icons

**Expected behavior**
Clicking on the icons should lead to the specified postion on the variant details page.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox 
 - Version 121

**Comment by stolpeo** [comment]
RCA
====

The issue persists with REEV, but the root cause is different. The router library is used to address the section to jump to, but the page builds too slowly as it is dynamically loaded so that the jump can't take place.

**Comment by stolpeo** [comment]
Solution proposal
=============

It is clear that we can't make router wait for the page to be loaded.

1. Either there is a possibility to get the jump position from the router call and execute it again after the page has fully loaded.
2. Or we store the jump position in the store when details are clicked and jump to it manually when the page finished loading.

**Comment by holtgrewe** [comment]
@stolpeo the router does not jump itself. Rather it passes a prop into the top level Vue view. That is, in the view you can wait/react on that prop and all stores to finish loading.

Be careful with watching store state, this often triggers loops. Rather set a periodic timer that runs every 100ms and jumps once after everything has loaded and then deactivates itself by some means.

**Comment by holtgrewe** [comment]
@stolpeo actually watching store state for jumping should be ok as we don't write. Calling into store on watching store state can be dangerous and should be done after careful consideration. E.g. done -> trigger load -> done ...
