### ISSUE TITLE
Flags and comments not visible in case overview annotations view

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#1375]
**Describe the bug**
Sequence variant flags and comments are stored in the database and displayed in the variant details page. However, they are not displayed in the case-wide variant annotation overview. An example is case `49fc975f-...` (full ID sent to @stolpeo).

**To Reproduce**
1. Go to the case overview of the case
2. Click on the variant annotations tab
3. See that no variants are colored and flags/comments icon is empty
4. Click on variant and see the comments and flags; also true for ACMG

**Expected behavior**
We want highlighting and displaying of flags, comments, ACMG.

**Screenshots**
N/A

**Additional context**
Presumably, the case-wide annotation result set is not properly managed.

We need to

- [x] #1377
- [x] #1378

**Comment by holtgrewe** [comment]
Need to

- fix current state (create a new management command)
- find root cause and ensure flagging works properly

**Comment by stolpeo** [comment]
Closing this umbrella ticket. :open_umbrella: -> :closed_umbrella:
