### ISSUE TITLE
Set order of quick presets in dropdown

### ISSUE THREAD

**Issue by xiamaz** [varfish-org/varfish-server#1479]
**Is your feature request related to a problem? Please describe.**
Currently the order of items in quick presets is determined by the order in which they were added.

**Describe the solution you'd like**
The order of quick presets should be customizable, which would allow users to keep quick presets in their preferred order.

**Describe alternatives you've considered**
None

**Additional context**
Allow dragging or manually setting a order key in the quick preset editor.

**Comment by einicke** [comment]
We want to integrate our SOP in Berlin.

**Comment by xiamaz** [comment]
The order icon cannot be dragged
