### ISSUE TITLE
Variant Details not working

### ISSUE THREAD

**Issue by flokraft85** [varfish-org/varfish-server#1509]
**Describe the bug**
After docker compose pull && docker compose up -d, to update to the lastest version, the Variant Details page only showing. 

No Gene
No Variant Information

It is the same for every SNV/InDel variant. For SV variants the details page work as expected.

**To Reproduce**
1. open a case
2. click on filter variants
3. click on a variant to open the Variant Details page
4. Variant Details page show only 
No Gene
No Variant Information

**Expected behavior**
Variant Details page should show the annotation details for s specific variant.

**Screenshots**
![grafik](https://github.com/varfish-org/varfish-server/assets/36499388/ebf9c818-3336-4da4-8ba1-a1e6a95c814c)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 123.0.1

**Comment by flokraft85** [comment]
There is maybe some error in the variant position "tranfer" from the "table" to the variant details page. When I try to use the IGV linkout, I got the following position in IGV "chrundefined:undefined-0". I'm not sure, if this is helpful, but maybe.

**Comment by stolpeo** [comment]
RCA
====

Had a VC with @flokraft85 . There seems to be an issue if the data uploaded already has a `chr` prefix in the chromosome field which causes the annonars call to fail:

```
proxy/varfish/annonars/annos/variant?genome_release=grch38&chromosome=chrchr1&pos=1234&reference=G&alternative=A
```

In addition, when HPO terms are provided, the call to viguno does not contain the list of HPO terms but just a `true` value. This very likely should be a list:

```
proxy/varfish/viguno/hpo/genes?gene_id=HGNC:1234&hpo_terms=true
```

**Comment by stolpeo** [comment]
RCA annonars
===========
bug lies within REEV. opening a new ticket there.

**Comment by stolpeo** [comment]
`&hpo_terms=true` is actually the correct call. Could reconstruct the issue locally.
