### ISSUE TITLE
Wrong genome build for IGV visualization of SV

### ISSUE THREAD

**Issue by flokraft85** [varfish-org/varfish-server#1511]
**Describe the bug**
The IGV tracks on the variant details page for SV show as source bed files which are GRCh37 and not GRCh38.

**To Reproduce**
n/a

**Expected behavior**
As the VarFish instance is cofigured to use GRCh37 and the data uploade to VarFish is GRCh38, GRCh38 data should be used.
For the transcript the GRCh38 data set is used.

**Screenshots**
![grafik](https://github.com/varfish-org/varfish-server/assets/36499388/8bc65d70-5570-474a-a9e9-54cc6a988fd1)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 123.0.1

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by stolpeo** [comment]
I assume that this is a follow-up error because the variant comments are not properly set up for the SVs. I will fix that error first and merge it, we will roll it out on your instance and see whether that helped. If no, I will create a follow-up ticket. @flokraft85
