### ISSUE TITLE
QC values thresholds should be adjustable

### ISSUE THREAD

**Issue by flokraft85** [varfish-org/varfish-server#1530]
**Is your feature request related to a problem? Please describe.**
It would be good, if the user can adjust the thresholds for the QC metrics (eg Coverage, % Duplicates, Ts/Tv), for coloring them in red (or perhaps other colors), if they are below or above a defined threshold. 
We currently have the problem, that for all our samples, the Ts/Tv ratio is colored in red, because it does not achieve the threshold value. However, I could not find this threshold and it should be adjustable to the local samples, because some QC values might be different from site to site.

**Describe the solution you'd like**
A possibly to add thresholds via an "options" page in the GUI or via a config file would be great.

**Describe alternatives you've considered**
n/a

**Additional context**
![grafik](https://github.com/varfish-org/varfish-server/assets/36499388/8538ac12-cbe2-41c6-b6e3-9ed6286a1c0f)

**Comment by einicke** [comment]
This should be adjustable on Project level
