### ISSUE TITLE
GBA1 gene validates positiv in gene allowlist but negative during query 

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-server#1532]
**Describe the bug**
The gene name GBA1 validates positive in the filter frontend when submitted to the gene allowlist but negative when the query starts (the serializer is responsible for this).  Apparently the mechanism for validation differs for frontend and for the serializer. This should be fixed that both are consistent in their validation.

https://github.com/varfish-org/varfish-server/blob/main/variants/serializers/__init__.py#L72 

**To Reproduce**
1. Go to Genes & Region on filter page
2. Enter GBA1
3. Submit query

**Comment by xiamaz** [comment]
@stolpeo Unfortunately the ticket was not the project. I have given it P0, please give a size estimate and try to include in next iteration if possible.

**Comment by stolpeo** [comment]
Sorry I missed that. I'll try to configure the repos in such a way that tickets are automatically added to the project.
