### ISSUE TITLE
ClinVar database dump update

### ISSUE THREAD

**Issue by einicke** [varfish-org/varfish-server#1533]
**Is your feature request related to a problem? Please describe.**
We need latest ClinVar database dumps. It needs to be recorded on which version 

**Describe the solution you'd like**
Get ClinVar Updates every week.
Dokument ClinVar Version if case is filtered.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by holtgrewe** [comment]
Usually downloaded automatically here

https://github.com/varfish-org/clinvar-data-jsonl

Using this

https://github.com/varfish-org/clinvar-this

Needs adjustment to new schema with the somatic update...

**Comment by einicke** [comment]
Steps to be done

- convert novel clinvar XML format into JSONL based on protobuf schema (clinvar-this)
- update GitHub actions CI to use novel clinvar-this (clinvar-data-jsonl)
- convert JSONL into rocksdb and aggregated data for annonars (annonars)
- update GitHub actions CI to write to rocksdb (annonars-data-jsonl)

**Comment by holtgrewe** [comment]
This is done now.
