### ISSUE TITLE
HTTP Error 500 when creating gene panel

### ISSUE THREAD

**Issue by flokraft85** [varfish-org/varfish-server#1537]
**Describe the bug**
I added some gene panel, which all worked fine. However, on certain gene panel cause a HTTP 500 error, when I try to createt it. I try to adjust name and version, so seems to be not related to this.

**To Reproduce**
1. Go to Gene Panels in the drop down menu
2. click "add panel"
3. Fill in Identifier, Version mjor, Version minor, Category and Title
4. Fill in the Genes
5. click on Create
6. after a short loading period I got the HTTP 500 error

**Expected behavior**
Should create a gene panel, like for all the other ones I created.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Edge
 - Version 111.0.1661.41

**Smartphone (please complete the following information):**

**Additional context**
Gene list for the panel

ACD
ACTRT1
ADM
AIP
AKT1
ALK
ANKRD26
APC
AR
ATM
AXIN2
BAP1
BARD1
BLM
BMPR1A
BRAF
BRCA1
BRCA2
BRIP1
BUB1
BUB1B
BUB3
CASR
CBL
CDC73
CDH1
CDK4
CDKN1B
CDKN1C
CDKN2A
CEBPA
CHEK2
CREBBP
CTC1
CTNNA1
CTR9
CYLD
DDB2
DDX41
DICER1
DIRAS3
DIS3L2
DKC1
DOCK8
EGFR
ELANE
ELP1
ENG
EPCAM
ERCC1
ERCC2
ERCC3
ERCC4
ERCC5
ESR1
ESR2
ETV6
EXT1
EZH2
FAN1
FANCA
FANCB
FANCC
FANCD2
FANCE
FANCF
FANCG
FANCI
FANCL
FANCM
FAS
FH
FLCN
FOXE1
FOXO1
FOXO3
GALNT12
GATA1
GATA2
GBA
GDNF
GNAS
GPC3
GPC4
GPR161
GREM1
H19
HABP2
HAX1
HNF1A
HOXB13
HRAS
IGF2
ITK
KCNQ1OT1
KIF1B
KISS1R
KIT
KITLG
KRAS
LEMD3
LIG4
LZTR1
MAD2L2
MAP2K1
MAP2K2
MAX
MCM8
MDH2
MEN1
MET
MINPP1
MITF
MLH1
MRE11
MSH2
MSH3
MSH6
MTAP
MTCP1
MUTYH
NAF1
NBN
NDUFA13
NF1
NF2
NFIX
NHP2
NKX2-1
NOP10
NOTCH3
NRAS
NSD1
NTHL1
NTRK1
PALB2
PARN
PAX3
PAX5
PAX6
PAX7
PDGFRA
PDGFRB
PHOX2B
PIK3CA
PMS1
PMS2
POLA1
POLD1
POLE
POLH
POT1
PPM1D
PPP1CB
PRF1
PRKACA
PRKACB
PRKAR1A
PRSS1
PTCH1
PTCH2
PTCSC1
PTCSC3
PTEN
PTPN11
PTPN12
RABL3
RAD50
RAD51
RAD51C
RAD51D
RAD54L
RAF1
RB1
RECQL4
REST
RET
RHBDF2
RIT1
RMRP
RNF43
RPL11
RPL15
RPL23
RPL26
RPL27
RPL31
RPL35A
RPL36
RPL5
RPS10
RPS15
RPS17
RPS19
RPS20
RPS24
RPS26
RPS27
RPS27A
RPS28
RPS29
RPS7
RRAS2
RTEL1
RUNX1
SAMD9L
SBDS
SDHA
SDHAF2
SDHB
SDHC
SDHD
SEC23B
SEMA4A
SH2B3
SHOC2
SLC26A3
SLC5A5
SLX4
SMAD4
SMAD9
SMARCA4
SMARCB1
SMARCE1
SOS1
SOS2
SPINK1
SPRED1
SQSTM1
SRC
SRGAP1
SRRM2
STAT3
STK11
STN1
SUFU
TERC
TERF2IP
TERT
TG
TINF2
TMEM127
TNFRSF11A
TP53
TRIM28
TRIP13
TSC1
TSC2
TSR2
UBE2T
VHL
WAS
WRAP53
WRN
WT1
XPA
XPC
XRCC2

**Comment by xiamaz** [comment]
@flokraft85 The issue is that GBA needs to be GBA1. Could you please try?

**Comment by xiamaz** [comment]
@stolpeo We need to have informative errors in the gene list field. The user should be able to see problematic entries even when entering very long gene lists.

**Comment by flokraft85** [comment]
Hi Max,
yes, sorry for this stupid mistake. 
For all the other genes, which could not resolve due to wrong names or wrong low or upper cases (maybe it would be easier to remove the case sensitivity for the gene name. I struggled with the C2orfXX, because the ORF was in upper cases in our lists, but in the official gene name is in in lower case) I got the message, that the gene name is wrong. Thats why I thought it would be another problem with this gene list.
However, using GBA1 instead of GBA solve the HTTP 500 error, but I still cannot create the list. Now GBA1 is shown in red under the gene list field.
![grafik](https://github.com/varfish-org/varfish-server/assets/36499388/d3c3211a-553d-41f4-8268-91a75e91a303)

**Comment by xiamaz** [comment]
@stolpeo Probably the other place where we still have the old gene lists.

@flokraft85 Danke für die Info! Das GBA Problem hatten wir auch schon intern. Als Workaround ist es aktuell möglich über die Quick Presets auch Genlisten als Preset abzuspeichern. Falls dies ausreichend ist. Aktuell müsste man dann nur den Fall manuell auf das neue Query Preset umstellen. Wir arbeiten aber daran, dass dies bald pro Projekt einstellbar ist.

**Comment by flokraft85** [comment]
@xiamaz Danke für den Workaround. Den werden wir testen.

**Comment by holtgrewe** [comment]
We only support genes with an HGNC ID.

All such gernes will have an NCBI and Ensg id.

https://genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:19159

Have we switched away from Django models for genes yet I favour of annonars queries?

**Comment by stolpeo** [comment]
Currently I replace dependencies to the Hgnc table as required. There is also a ticket for that #1551 , but IIRC there are some dependencies where it was a bit convoluted or a dependency to Hgnc in a recent feature implementation I wasn't sure about replacing.

**Comment by stolpeo** [comment]
Accidentally solved with #1622 :weary:
