### ISSUE TITLE
Remove references to old HGNC Gene table in Varfish

### ISSUE THREAD

**Issue by xiamaz** [varfish-org/varfish-server#1551]
**Is your feature request related to a problem? Please describe.**
Currently we validate genes against either mehari or the hgnc table.

**Describe the solution you'd like**
Everything should use mehari.

**Comment by stolpeo** [comment]
In a first step, I assembled a list of references to the HGNC table.

**clinvar_export/serializers.py**

https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/clinvar_export/serializers.py#L350
=> function not used anymore
https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/clinvar_export/serializers.py#L357
=> function not used anymore

**geneinfo/models.py**

https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/geneinfo/models.py#L133
=> function not used anymore

Is geneinfo app used in general? Yes, for resolving genepanels

**geneinfo/views_api.py**

https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/geneinfo/views_api.py#L23
=> view not used anymore 

**geneinfo/views.py**

On a related note: is `RefseqToHgnc`/`RefseqToEnsembl` used? yes by `ExtendQueryPartsHgncJoin`

https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/geneinfo/views.py#L83
=> view not used anymore

**variants/queries.py**

https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/variants/queries.py#L210
=> definitely used

https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/variants/queries.py#L1040
=> definitely used

**variants/models/userannos.py**

https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/variants/models/userannos.py#L26
-> `GetGeneSymbolsMixin` -> `SmallVariantComment`/`SmallVariantFlags` => definitely used

**geneinfo/tests/_test_views.py**

**geneinfo/tests/test_models.py**

**variants/tests/_fixtures.py**

**variants/tests/test_queries.py**

=> usage in tests is not critical

**Comment by stolpeo** [comment]
Is `geneinfo` app used in general? Yes, for resolving genepanels

On a related note: is `RefseqToHgnc`/`RefseqToEnsembl` used? yes by `ExtendQueryPartsHgncJoin`

**Comment by stolpeo** [comment]
- Use annonars to resolve gene panels

**Comment by stolpeo** [comment]
Not resolved yet:
- https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/clinvar_export/serializers.py#L350
- https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/clinvar_export/serializers.py#L357
- https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/variants/queries.py#L210
- https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/variants/queries.py#L1040

Will merge and open a new ticket for the remaining.
