### ISSUE TITLE
CADD score for InDels not working

### ISSUE THREAD

**Issue by flokraft85** [varfish-org/varfish-server#1555]
**Describe the bug**
Although "Pathogenicity Prioritization ->Enable variant pathogenicity-based prioritization" is activated, which should lead to a calculation of CADD scores for, no CADD scores for InDels are shown in the variant table. 

**To Reproduce**
1. Open a case
2. click on "Prioritization"
3. check the box "Enable variant pathogenicity-based prioritization"
4. click Filter&Display

**Expected behavior**
VarFish should calculate CADD scores for InDels used for CADD-base variant prioritization.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 123.0.1

**Additional context**
No error message is display in the logs of the GUI. No errors could be found in the logs of the varfish-docker-compose-cadd-rest-api-worker.
The output of the CADD script is a vcf with not "chr" before the chromosomal positions. Maybe VarFish expect chromosomal positions with "chr"? But just a wild guess.

**Comment by stolpeo** [comment]
Cannot reproduce it, I need to look into @flokraft85 instance to track it down.

**Comment by stolpeo** [comment]
To note is that it is a partial problem, some indels seem to be scored while SNPs seem to be always scored.

**Comment by stolpeo** [comment]
The imported variants in the Aachen instance are not normalized/left aligned for indels. CADD is doing that when returning the scores and thus the variants do not match anymore so the scores can't be assigned, e.g.:

```
1-1234-ATC-AC => 1-1234-TC-C
```

We recommend using bcftools norm before importing the data into VarFish.

```
bcftools norm input.vcf.gz -m- -a -Oz9 -o output.vcf.gz
```
