### ISSUE TITLE
PubTator is not working

### ISSUE THREAD

**Issue by flokraft85** [varfish-org/varfish-server#1556]
**Describe the bug**
The PubTator widget on the variant details page show an error instead of variant/gene related information.
"Error loading PubTator 3 data: Error: Error running PubTator 3 search: InvalidResponseContent: failed to parse PubTator 3 export: TypeError: l[c.pmid] is undefined"

**To Reproduce**
1. Open a case
2. click on Filter&Display
3. click on a variant in the list
4. scroll down on the variant details page to the PubTator widget

**Expected behavior**
PubTator should show gene or variant related literature.

**Screenshots**
![grafik](https://github.com/varfish-org/varfish-server/assets/36499388/5c646191-4ab1-48d7-9ffc-12491461a5f2)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 124

**Comment by xiamaz** [comment]
Issue also exists in Berlin

**Comment by xiamaz** [comment]
Works again. Re-open if issue persists.
