### ISSUE TITLE
igv.js view on variant details page does not "jump" to SV position

### ISSUE THREAD

**Issue by flokraft85** [varfish-org/varfish-server#1560]
**Describe the bug**
The IVG view on the variant details page for SV (GRCh38) shows the whole genome (chr1-22, X and Y) instead showing the region, where the SV is localized. Region is set to all. 
I can enter the position manually in the IGV view (eg chr1:20,605,522-20,606,197) and then the IGV jumps to the correct position. However, the tracks which are shown for GRCh37, eg DGV, gnomAD SV ... are not visible. Maybe the bed files for the tracks are missing for GRCh38?
Something really weird happened, if I scroll during loading of the SV variant details page. Then the IGV view shows the "right" position, but with the hg19 genome build. Which is of cause then the wrong position in this genome build. Maybe related to https://github.com/varfish-org/varfish-server/issues/1525 

**To Reproduce**
1. open a case
2. click on "Filter SV"
3. click on "Filter&Display"
4. click on a variant in the list
5. scroll to IVG view on variant details page

**Expected behavior**
IGV view should show the position matching to the SV and should show tracks indicating SV in this region from gnomAD SV, DGV etc. 

**Screenshots**
IGV view only show "all"
![grafik](https://github.com/varfish-org/varfish-server/assets/36499388/b7e09685-70f6-4ce0-bea6-de27416c2c52)
IGV view after manually entering the position
![grafik](https://github.com/varfish-org/varfish-server/assets/36499388/e47d0d39-5cd8-4764-90fa-c49cb18b12fd)
IGV view with hg19, after scrolling during variant details page loading
![grafik](https://github.com/varfish-org/varfish-server/assets/36499388/6f94d767-404b-4602-ad77-2646ad2ff2db)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox 
 - Version 124.0.0

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by stolpeo** [comment]
Will be closed with https://github.com/bihealth/reev-frontend-lib/pull/203
