### ISSUE TITLE
effects "all" does not catch empty annotations

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-server#1578]
Setting the effects to catch all annotations (`all`) (also used by preset `impact` to `any`) does not include variants that have no annotation at all. Users expect to catch all variants when they loosen the settings as much as possible. The postgres query looks like this;

```
variants_smallvariant.refseq_effect && cast(array[
   "3_prime_UTR_exon_variant",
   "3_prime_UTR_intron_variant",
   "5_prime_UTR_exon_variant",
   "5_prime_UTR_intron_variant",
   "coding_transcript_intron_variant",
   "complex_substitution",
   "direct_tandem_duplication",
   "disruptive_inframe_deletion",
   "disruptive_inframe_insertion",
   "downstream_gene_variant",
   "exon_loss_variant",
   "feature_truncation",
   "frameshift_elongation",
   "frameshift_truncation",
   "frameshift_variant",
   "inframe_deletion",
   "inframe_insertion",
   "intergenic_variant",
   "internal_feature_elongation",
   "missense_variant",
   "mnv",
   "non_coding_transcript_exon_variant",
   "non_coding_transcript_intron_variant",
   "splice_acceptor_variant",
   "splice_donor_variant",
   "splice_region_variant",
   "start_lost",
   "stop_gained",
   "stop_lost",
   "stop_retained_variant",
   "structural_variant",
   "synonymous_variant",
   "transcript_ablation",
   "upstream_gene_variant"
]::varchar[] AS varchar[])
``` 

It should also be valid if no annotation is available in case all is set.

**Comment by stolpeo** [comment]
Not sure if we really want this or if this would cause to much artifacts. There could also be just a checkbox to disable the effect filter in the query so it shows even not annotated variants. I guess this is up for discussion.

**Comment by xiamaz** [comment]
If users select all they might have very small regions of interest. I think this should be ok. Too many artifacts should be caught by Quality filters, not by this one.

**Comment by stolpeo** [comment]
If the question comes up, disabling all effects shows no variants (as expected) `variants_smallvariant.refseq_effect && cast('{}'::varchar[] AS varchar[])`, because an entry does not overlap with anything in an empty list.

**Comment by xiamaz** [comment]
@holtgrewe Should every variant in mehari theoretically have an annotation or is no annotation sane behavior?

**Comment by xiamaz** [comment]
@stolpeo In default behavior "all" should also return unannotated variants. In this specific instance we also have annotation issues, so there might also be some resulting mehari changes.

**Comment by stolpeo** [comment]
OK, could you prioritize this ticket? @xiamaz

**Comment by xiamaz** [comment]
Prioritized. If change is small please handle soon, as this might allow users to work around potentially significant mehari annotation issues.
