### ISSUE TITLE
remove hgmd app

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-server#1627]
With ticket #739 I removed references to HGMD application/database and created a migration to remove the hgmd table. When this is deployed in production, we can finally remove the hgmd app.

**Comment by xiamaz** [comment]
MH: We have imported HGMD entry ensembl, this based on HGMD public info (will be obsolete if we switch to rust)

MH: **HGMD Table and App can be removed**

MH: Linkout to HGMD should be possible. **User-profile setting should have configurable HGMD URL**. This should be user configurable. Is in the (small) variants app.

MH: We need to have good configuration cascade, will be in new ticket.

**Comment by xiamaz** [comment]
Will be postponed to make upgrade to new versions easier.

**Comment by xiamaz** [comment]
After discussion, we will leave the app only with migrations and sufficient comments, so that these will not interfere with upgrades.
