### ISSUE TITLE
previous query settings might interfer with current settings

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-server#1629]
**Describe the bug**
When I removed hgmd and dbnsp filter settings as requested in #739 I noticed that the settings are stuck to previous query settings and the only solution was to remove them manually in the database from previous queries (this is also encapsulated in a database transaction to solve the issue). While it is expected behaviour that the previous query settings are loaded, we should erase the query settings in the store when selecting quick presets to not accidentally carry on old data.

**Comment by xiamaz** [comment]
MH: Format of query settings need to be versioned. Current timepoint will be version 0.

MH: We will need migration code between versions. Short term solution is to just reset to default in new version.

We will add major and minor version field. We will increment minor version first. once we have protobuf, we will use semver and we will increment minor if forward/backward compatible and we will use major if these break.

TODO:

- [ ] add long term ticket for including migration code between versions
