### ISSUE TITLE
HGMD Pro link-out missing in the vue interface

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-server#1632]
**Is your feature request related to a problem? Please describe.**
The HGMD Pro link-out can be enabled in the configuration and configured with a custom URL, but this is never used. Likely it was implemented in the old interface, but didn't make it to the new one, as mentioned in #739.

https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/config/settings/base.py#L563

We need to either implement the link-out or discuss the usage. It was briefly mentioned in the meeting today, but I can't recall if we had any solution.

**Comment by xiamaz** [comment]
After discussion, this configuration option should be removed.
