### ISSUE TITLE
Removal of dependencies to geneinfo app 

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-server#1635]
**Is your feature request related to a problem? Please describe.**
The `geneinfo` app isn't used much anymore, expect for resolving gene panels. This can be done with a call to `annonars`. Double check for other usages of the app.

**Comment by xiamaz** [comment]
@stolpeo Could you check for current usage of the `geneinfo` app and how these can be modeled using annonars? Potentially in discussion with manuel.

**Comment by holtgrewe** [comment]
annonars can help here, example of public reev

- https://reev.cubi.bihealth.org/internal/proxy/annonars/genes/lookup?q=BRCA1
- https://reev.cubi.bihealth.org/internal/proxy/annonars/genes/lookup?q=HGNC:1100
- https://reev.cubi.bihealth.org/internal/proxy/annonars/genes/lookup?q=ENSG00000012048
- https://reev.cubi.bihealth.org/internal/proxy/annonars/genes/lookup?q=672

**Comment by xiamaz** [comment]
Will be discussed between @stolpeo and @holtgrewe

**Comment by xiamaz** [comment]
Remaining todo

- resolution of HPO-Terms

@stolpeo Will complete currently remaining work to reduce dependencies to `geneinfo` app.
