### ISSUE TITLE
Finalize "cases_seqvars" module

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#1738]
**Is your feature request related to a problem? Please describe.**
In #1737 we added a minimal implementation of the Seqvars module. Tests and permissions are missing.

**Describe the solution you'd like**
- [ ] add tests
- [ ] add permission checks and tests
- [ ] include module endpoint views in URLs independent of `VARFISH_GEN2_ANALYSIS` setting

**Describe alternatives you've considered**
N/A

**Additional context**
- #1737

**Comment by xiamaz** [comment]
@holtgrewe Will update project status and handle ticket

**Comment by holtgrewe** [comment]
Will handle tests and permissions already in #1737
