### ISSUE TITLE
Make OMIM search case insensitive

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#1788]
**Is your feature request related to a problem? Please describe.**
The latest viguno version allows to enable case insensive search (see brand new swagger docs). We don't use it.

**Describe the solution you'd like**
Use case insensitive search in the UI.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by stolpeo** [comment]
I'm taking over this @xiamaz @einicke as I have been working a related issue lately, I consider it to be a minor change that does not consume too much time + there are no more small tickets for me in the pipeline.
