### ISSUE TITLE
Entering OMIM terms in case phenotype does not work

### ISSUE THREAD

**Issue by xiamaz** [varfish-org/varfish-server#1792]
**Describe the bug**
Users are able to enter OMIM ids as phenotype terms in the case overview.

**To Reproduce**
Enter a case and try to enter OMIM term into phenotype for an individual in a case.

**Expected behavior**
The correct omim term with matching id or matching description should be presented as a suggestion. Pasted omim terms should be retained in the phenotype list.

**Comment by holtgrewe** [comment]
Fixed, please try as well.
