### ISSUE TITLE
Sort case search results

### ISSUE THREAD

**Issue by xiamaz** [varfish-org/varfish-server#1810]
Currently a perfect match might not be the first result. This should not be the case. Consider introducing a result table field with match score and sort by that column

**Comment by xiamaz** [comment]
Use case:

This should find this: `LB11-1111` <-> `LB11_1111`

**Comment by xiamaz** [comment]
In original design tokens were removed, but this stopped working in the meantime.

**Comment by stolpeo** [comment]
related to #1810, closed with #1812
