### ISSUE TITLE
HPO Terms not findable

### ISSUE THREAD

**Issue by einicke** [varfish-org/varfish-server#1814]
**Describe the bug**
HPO terms are not shown even if the writen term is entered with perfect match

**To Reproduce**
1.Open any case
2. Go to HPO Lookup in Case-Overview or Phenotype Prioritization
3. Search for "short stature"
4. See no result
5. Enter HP:0004322
6. See term "HP:0004322 - Short stature"

**Expected behavior**
HPO Terms should be searchable by written term. No one knows the HP:XXXXXXX Number by heart.

**Comment by stolpeo** [comment]
Are OMIM terms relevant? Should they show up in the search?

**Comment by stolpeo** [comment]
Henrike reported that OMIM terms are only relevant in the case overview and I believe you said something similar.
