### ISSUE TITLE
Seqvars Pathogenicity Priorization Settings

### ISSUE THREAD

**Issue by Gregoor** [varfish-org/varfish-server#1820]
According to UI, those fields would be needed:
```ts
type SeqvarsPathogenicityPrioSettings = {
  enabled: boolean
  priorization_score: 'CADD' | 'REVEL' | 'MutationTaster' | 'UMD Predictor'
}
```

There might also be presets for it, but those I can not infer from what I know

**Comment by holtgrewe** [comment]
For presets cf.

https://github.com/varfish-org/varfish-server/blob/main/backend/seqvars/factory_defaults.py#L698

**Comment by Gregoor** [comment]
Aaah thanks! So in that context I can read variant as meaning pathogenic, makes sense
