### ISSUE TITLE
Improve visibility of hide button for new UI sidebar

### ISSUE THREAD

**Issue by xiamaz** [varfish-org/varfish-server#1854]
The current burger menu button for hiding the sidebar is difficult to find for users. I'll propose some alternatives

**Comment by xiamaz** [comment]
@stolpeo Good alternative solution is non-straightforward.

**Comment by holtgrewe** [comment]
Related

- #1875 
- #1877

**Comment by holtgrewe** [comment]
Closing in favour of #1877 (set to auto-merge in #1881).
