### ISSUE TITLE
Impact not updated when quick presets are updated

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#2014]
**Describe the bug**
For a particular case (details in internal chat), impact is not adjusted when quick presets are changed.

**To Reproduce**
See internal channel.

**Expected behavior**
Impact should be changed.

**Additional context**
N/A

**Comment by holtgrewe** [comment]
@stolpe can you do a RCA?

**Comment by stolpeo** [comment]
RCA
===

If a quick preset exists that has not set a value for at least one of the settings and this quick preset is selected, the javascript throws an error and creates an inconsistent state that causes all subsequent quick preset selections to fail. The line that is causing this is located here:

https://github.com/varfish-org/varfish-server/blob/911c18124ea49b5f82a36d77fd46875bf4ed5ead/frontend/src/variants/components/FilterForm/QuickPresets.vue#L257

**Comment by stolpeo** [comment]
Solution
======

1. This kind of error should be caught in that function
2. We enforce that all settings in a quick presets must be set

**Comment by stolpeo** [comment]
RCA 2
=====

There is another error that only displays the preset sets in the editor once a case from the project was loaded. It fails if you go directly to the editor (when reloading the page for example) because the caseListStore is only initialized when a case was loaded. Fix is easy.
