### ISSUE TITLE
Annotated SV now showing up in case annotations

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#2015]
**Describe the bug**
Flagged SVs not showing up in case annotations.

**To Reproduce**
See internal chat.

**Expected behavior**
SV should be colored.

**Additional context**
N/A

**Comment by holtgrewe** [comment]
@stolpeo can you do a RCA and hopefully fix?

**Comment by stolpeo** [comment]
The issue was understood wrongly. Changed description and title
