### ISSUE TITLE
Joint Filtration does not work for large cohorts

### ISSUE THREAD

**Issue by sczakihl** [varfish-org/varfish-server#241]
**Describe the bug**
When performing a joint query on the a large cohort, the query cancels with an error message.

**To Reproduce**
1. Go to Namse project
2. Click joint filtration
3. Start filtration

**Expected behavior**
Obtaining a result list when finished filtering.

**Screenshots**

```
error message:  [2021-11-12 10:27:50] Joint project filter query and store results. file failed: (psycopg2.errors.DiskFull) could not resize shared memory segment "/PostgreSQL.1402429173" to 57490496 bytes: No space left on device [SQL: SELECT variants_smallvariant.id, variants_smallvariant.release, variants_smallvariant.chromosome, variants_smallvariant.chromosome_no, variants_smallvariant.start, variants_smallvariant."end", variants_smallvariant.bin, variants_smallvariant.reference, variants_smallvariant.alternative, variants_smallvariant.ensembl_gene_id AS ensembl_gene_id, variants_smallvariant.refseq_gene_id AS entrez_id, variants_smallvariant.refseq_transcript_id, variants_smallvariant.refseq_hgvs_c, variants_smallvariant.exac_frequency, variants_smallvariant.gnomad_exomes_frequency, variants_smallvariant.gnomad_genomes_frequency, variants_smallvariant.thousand_genomes_frequency, variants_smallvariant.exac_homozygous, variants_smallvariant.gnomad_exomes_homozygous, variants_smallvariant.gnomad_genomes_homozygous, variants_smallvariant.thousand_genomes_homozygous, variants_smallvariant.exac_heterozygous, variants_smallvariant.gnomad_exomes_heterozygous, variants_smallvariant.gnomad_genomes_heterozygous, variants_smallvariant.thousand_genomes_heterozygous, variants_smallvariant.genotype, variants_smallvariant.set_id, variants_smallvariant.in_clinvar, variants_smallvariant.var_type, variants_smallvariant.ensembl_effect != variants_smallvariant.refseq_effect AS effect_ambiguity, variants_smallvariant.refseq_hgvs_p AS hgvs_p, variants_smallvariant.refseq_hgvs_c AS hgvs_c, variants_smallvariant.refseq_transcript_coding AS transcript_coding, variants_smallvariant.refseq_effect AS effect, variants_smallvariant.refseq_gene_id AS gene_id, variants_smallvariant.refseq_transcript_id AS transcript_id, variants_smallvariant.refseq_exon_dist AS exon_dist, variants_smallvariant.ensembl_transcript_id, variants_case.sodar_uuid AS case_uuid, variants_case.name AS family_name, coalesce(dbsnp_subquery.rsid, NULL) AS rsid, coalesce(mtdb_subquery.mtdb_count, %(coalesce_1)s) AS mtdb_count, coalesce(mtdb_subquery.mtdb_frequency, %(coalesce_2)s) AS mtdb_frequency, coalesce(mtdb_subquery.mtdb_dloop, %(coalesce_3)s) AS mtdb_dloop, coalesce(helixmtdb_subquery.helixmtdb_het_count, %(coalesce_4)s) AS helixmtdb_het_count [...]
```

**Comment by stolpeo** [comment]
### Root Cause Analysis

The number of cases in the Namse cohort is large (508). As the error message suggests, the query has problems with the shared memory/a full disk:

```
file failed: (psycopg2.errors.DiskFull) could not resize shared memory segment "/PostgreSQL.1402429173" to 57490496 bytes: No space left on device
```

Therefore, I'm trying to figure out the number of cases from which on this error occurs:

Query with 254 cases:
Query with 127 cases:
Query with 64 cases:

**Comment by stolpeo** [comment]
**Resolution Proposal**

As an intermediate solution, catch the error message and display a more human readable message "Too many cases, try rerun with less cases".

**Affected Components**

- VarFish server

**Affected Modules/Files**

- `variants/queries.py`

**Required Architectural Changes**

None.

**Resolution Sketch**

e.g. Change X in F. Then do Y.

**Comment by holtgrewe** [comment]
**Further Root Cause Analysis**

A further look into this showed an error message (probably after increasing shared memory).

```
(psycopg2.errors.ProgramLimitExceeded) too many range table entries
```

- https://stackoverflow.com/a/53522903/84349

**Comment by holtgrewe** [comment]
**Resolution Proposal**
I would be more optimistic here than the previous resolution proposal. We should get away with reducing the number of `UNION` queries. We can create a sequence of queries from the Python code and concatenate the results afterwards.

**Affected Components**

- VarFish server

**Affected Modules/Files**

- `variants/views.py`

**Required Architectural Changes**

None.

**Resolution Sketch**
- introduce new setting `VARFISH_QUERY_MAX_UNION` default `20`
- split case list into batches of `VARFISH_QUERY_MAX_UNION` and perform query on each
- concatenate results after querying

**Comment by holtgrewe** [comment]
I'm now getting the diskful problem again although, we configure the postgres container to have up to 1gb of shm.

**Comment by holtgrewe** [comment]
It looks to me that the original query succeeded but varfish now has trouble fetching the results but I'm not certain.

**Comment by holtgrewe** [comment]
PR #372 got rid of the memory problem as the required temporary storage is greatly reduced. So one problem less ... and the next one pops up!

Loading the prefetch results for a thousand cases takes too long for displaying. I think we cannot solve this for 1.x and have to cap the maximal project and cohort subject query sizes which is #374.

We need to re-think the backend and front-end/UI for queries to larger number of cases.

Putting this for 2.x branch.

**Comment by holtgrewe** [comment]
Feature removed for now, will be added back later.
