### ISSUE TITLE
Adjust "de novo" preset

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#292]
**Is your feature request related to a problem? Please describe.**
When using the current preset “de novo” the index and the parents are set to `0/0`. This will exclude _de novo_ hemizygous variants.

**Describe the solution you'd like**
Use the setting: variant (index), non-variant or 0/0 (parents).

With this settings we would also find the de novo x-chromosomal variants in males (index=1/1 and parents: 0/0 are missed by currently used de novo preset and also not displayed by x-chromosomal settings (index 1/1, mother 0/1).

**Describe alternatives you've considered**
N/A

**Additional context**
- From internal helpdesk.

**Comment by xiamaz** [comment]
Are there plans to make presets in general configurable?

Specifically LB deals mostly with mono-exomes and a larger focus on panel assessments. It would be great if teams or individual investigators could add these as other presets and possibly remove the current default presets.

**Comment by holtgrewe** [comment]
@xiamaz No. The settings have been agreed on with N.E. and are part of the LB/Charite SOP to the best of my knowledge.

**Comment by holtgrewe** [comment]
We now have configurable presets.
