### ISSUE TITLE
Properly handle ClinVar updates

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#33]
**Is your feature request related to a problem? Please describe.**
We need to properly handle Clinvar updates. When the Clinvar background data table is updated then we need to update all cases.

**Describe the solution you'd like**
We need to add versions to the Clinvar background data table. On import, we need to reannotate the cases. Users should be notified about reclassified variants in their cases.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by your-highness** [comment]
joining in
