### ISSUE TITLE
Mode of Inheritance in VarFish ClinVar export is not up to date with allowed values in ClinVar

### ISSUE THREAD

**Issue by ahujameg** [varfish-org/varfish-server#380]
**Describe the bug**
The option list for the 'Mode of Inheritance' in VarFish ClinVar export contains the option list which is not up to date with the allowed values in ClinVar.

**To Reproduce**
1. Go to ClinVar export feature
2. Create a new submission set or edit an existing one.
3. Open a variant.
4. Check the options available in the drop-down of 'Mode of Inheritance'.

**Expected behavior**
The list of options should contain the ones that are allowed in ClinVar:
https://ftp.ncbi.nlm.nih.gov/pub/GTR/standard_terms/Mode_of_inheritance.txt

**Desktop**
 - OS: Linux
 - Browser chrome, safari
 - Version 22

**Comment by holtgrewe** [comment]
Will be subsumed in #1300.
