### ISSUE TITLE
Implement launcher util

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#449]
**Is your feature request related to a problem? Please describe.**
Upgrading Varfish versions is currently a manual process. Also restart takes a long time. It would be nice to have some tool support for this.

**Describe the solution you'd like**
Implement a `launcher` script (maybe with accompanying Docker image) and add it to varfish-docker-compose to give users some tooling for:

- upgrading VarFish; support for
  - look for changes in `varfish-docker-compose` checkout and complain
  - check that the `main` branch is used
  - `git pull --rebase`
  - restarting the servers
- restarting the server
  - launch a maintenance notification server (cf [this blog post](https://dille.name/blog/2021/03/14/using-traefik-to-display-maintenance-information/))
  - do a `docker-compose pull`
  - do a restart (hard restart with down/up when `--hard-restart` is given)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by brand-fabian** [comment]
Are you aware of watchtower (https://github.com/containrrr/watchtower)? It seems to be relatively close to the upgrade feature you describe, esp. for a docker-compose use case.
