### ISSUE TITLE
Create a more uniform scoring system

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#454]
**Is your feature request related to a problem? Please describe.**
The different integrated scores are quit intimidating for new users. Also, it would be useful to have a more "uniform" scoring system that is capable of unifying the score ranges.

**Describe the solution you'd like**
Work on a unification of variant pathogenicity scores, e.g. in the range of 0.0 ... 1.0.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by xiamaz** [comment]
I like the approach *Franklin* chose for this issue:

![image](https://user-images.githubusercontent.com/3340720/165909653-12275a14-ca38-40eb-9547-06786a9261bf.png)

My main issues with the current varfish visualization, is that it might be difficult to synthesize the information from different scores. Color cues or a visual representation would be very helpful.

**Comment by holtgrewe** [comment]
Pejaver is useful here.
