### ISSUE TITLE
Provide ACMG classification support for SVs/CNVs

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#469]
**Is your feature request related to a problem? Please describe.**
There are ACMG classifications for CNVs. VarFish does not provide support for them.

**Describe the solution you'd like**
Implement support for annotating CNVs using the corresponding ACMG guidelines similar to how it is done for small variants.

**Describe alternatives you've considered**
N/A

**Additional context**
- [Technical standards for the interpretation and reporting of constitutional copy-number variants: a joint consensus recommendation of the American College of Medical Genetics and Genomics (ACMG) and the Clinical Genome Resource (ClinGen)](https://pubmed.ncbi.nlm.nih.gov/31690835/)
- #426

**Comment by xiamaz** [comment]
In first approximation just having the result classification benign, likely benign, VUS, likely pathogenic, pathogenic would be extremely helpful, as we currently are unable to properly annotate any identified SVs in Varfish, which blocks Clinvar transfer of SVs.

**Comment by stolpeo** [comment]
Will stop working on this. The vue code for structural variants differs too much from that for small variants.

**Comment by xiamaz** [comment]
Okay, no problem. We can discuss issues and longer term plan next thursday.
