### ISSUE TITLE
Allow for ACMG criteria grading

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#476]
**Is your feature request related to a problem? Please describe.**
After the ACMG criteria have been published many local labs and groups have started to create alternative ways of using them. One adjustment by *ClinGen Sequence Variant Interpretation Work Group* has been given in discussion #202. It allows to upgrade or downgrade each ACMG point as needed and document the upgrading/downgrading in either direction.

**Describe the solution you'd like**
We should implement this such that each point from the ACMG assessment can be easily graded. We should use the correct nomenclature. The user interface must be easy to use and allow users to easily identify adjustments.

**Describe alternatives you've considered**
N/A

**Additional context**
- Discussion triggering this: #202 
- Making ACMG configurable is mostly orthogonal but we cannot work on it in parallel: #477 
- Having more than one variant assessment per variant (up to one per user) has a similar orthogonality/dependency: #475

**Comment by xiamaz** [comment]
I will provide some context.

The original ACMG 2015 publication allows for changing the grade of individual criteria:

> In order to provide critical flexibility to variant classification, some criteria listed as one weight can be moved to another weight using professional judgment depending on the evidence collected. For example, rule PM3 could be upgraded to strong if there were multiple observations of detection of the variant in trans (on opposite chromosomes) with other pathogenic variants (see section PM3 for further guidance). In contrast, in situations when the data are not as strong as described, judgment can be used to consider the evidence as fulfilling a lower level (e.g. see PS4, Note 2 in [Table 3](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4544753/table/T3/)).

This is a general specification with no limit on the weights that might be set on individual criteria.

As a most common denominator, all pathogenic and benign criteria should be gradable at any weight in order to fully cover the possibilities allowed by ACMG.

**Comment by holtgrewe** [comment]
Closing, will harmonize towards REEV.
