### ISSUE TITLE
Gene-wide variation landscape

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#491]
**Is your feature request related to a problem? Please describe.**
It would be good to see the variation landscape within a gene. This should include gnomAD but also the in-house variant data. Data can be analyzed nicely with [lollipop plots](https://github.com/joiningdata/lollipops).

**Describe the solution you'd like**
Add a button that allows to see the mutational landscape of a gene in the result view. Clicking it, a modal opens that displays the variants in the background database with frequency using lollipop plots. The view should allow selecting for the appropriate transcript to plot. The view could also show the variants in gnomAD for this gene. The view could also display overlapping SVs.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by your-highness** [comment]
I highly support this features. It's great for designing subpanels based on a selected cohort!
