### ISSUE TITLE
Allow sorting structural variants by size

### ISSUE THREAD

**Issue by xiamaz** [varfish-org/varfish-server#506]
**Is your feature request related to a problem? Please describe.**
When filtering structural variants, I would like to view the largest SVs first, so as not to miss large deletions/duplications that might need to be investigated first.

**Describe the solution you'd like**
The table presenting variants should allow for sorting SVs by size in both descending and ascending order.

**Describe alternatives you've considered**
Exporting SVs to excel and doing it manually. This is a lot of work for a very common workflow.

**Comment by holtgrewe** [comment]
This should be fairly simple by using DataTable similar to how we do it for the small variants right now.
