### ISSUE TITLE
Tooltips do not disappear

### ISSUE THREAD

**Issue by xiamaz** [varfish-org/varfish-server#507]
**Describe the bug**
Currently a large number of items in varfish contain tooltips that appear on hover. However the toggling of tooltips currently is very buggy.

**To Reproduce**
1. Go to 'Filter variants'
2. Click on ACMG classification after filtering variants.
3. Click on one toggle, let tooltip appear
4. Hover over another tooltip, tooltip should disappear.

**Expected behavior**
Only a single tooltip should ever be visible at a single timepoint. Any tooltip should only remain, while the cursor is hovered over the element in question.

Alternatively no tooltips should exist whatsoever. They have bad discoverability and as of now are very intrusive and a main source of UI bugs.

**Screenshots**
![image](https://user-images.githubusercontent.com/3340720/168272258-d8197aec-672c-4758-97a0-10e4157e3709.png)

**Comment by holtgrewe** [comment]
Not relevant for Vue.js UI.
