### ISSUE TITLE
MutationTaster prioritization still broken.

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-server#514]
**Describe the bug**
After switching back to MT 85 for scoring, there is an html error page returned when a variant can't be predicted. This hasn't been the case before with the interface. This prevents the scoring with MT.

**To Reproduce**
1. Select variant prioritization with MT
2. Filter
3. There must be a variant present that MT can't predict
4. See `Single case filter query and store results file failed: 'id'`

**Expected behavior**
Variant prioritization with MT working.

**Comment by stolpeo** [comment]
E.g. this variant returns an error page while the web interface for the same variant delivers a prediction:

```
$ curl -d format=tsv -d debug=1 -d variants='1:883899T>G' https://www.genecascade.org/MTc85/MT_API.cgi
Tue May 31 09:14:21 2022Searching for results...result for 1,883899,T,G
xxx1,ENST00000327044,26155,3,simple_aae,955,,,,,0,0,0,25815077
Tue May 31 09:14:21 2022Finding transcripts
Trying to map 1 variants without prediction to Ensembl transcripts
1,883899,T,G
1,1,00000327044,10790,10792,C
1 variant:transcript pairs
0 variants not mapped to transcripts - either outside of known gene or (if option specified) outside / distant from exon
<h1>Software error:</h1>
<pre>Can't locate object method &quot;new&quot; via package &quot;MutationTaster&quot; (perhaps you forgot to load &quot;MutationTaster&quot;?) at /www/MutationTaster85/cgi-bin/MT_API.cgi line 266.
</pre>
<p>
For help, please send mail to the webmaster (<a href="mailto:dominik.seelow@charite.de">dominik.seelow@charite.de</a>), giving this error message 
and the time and date of the error.

</p>
```

https://www.genecascade.org/MT85/ChrPos85.cgi?chromosome=1&position=883899&ref=T&alt=G

So far, Dominik hasn't responded to the error report. As far as I got it, the MT scoring feature is not used. Either we drop it completely, or just implement it for MT 2021.

**Comment by stolpeo** [comment]
We should consider not repairing the connection to the MT interface for scoring/prioritization as the API is not reliable. The suggestions would be to favour CADD scoring instead. However, the setup for CADD involves a large download which includes data we do not require. We should discuss with AG Kircher whether it is possible to strip down the downloads to include only the scoring.

**Comment by stolpeo** [comment]
Martin has been contacted.

**Comment by holtgrewe** [comment]
I agree with @stolpeo and we should target the bollonaster branch.

**Comment by your-highness** [comment]
> I agree with @stolpeo and we should target the bollonaster branch.

No backport to Athena intended? It would be great to have the functionality of the scoring (maybe by skipping variants that can't be predicted)

**Comment by holtgrewe** [comment]
MutationTaster support removed for now.
