### ISSUE TITLE
Re-rendering of ag-grid table does not work

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-server#699]
**Describe the bug**
When a variable the results changes, it triggers a re-rendering of the row that has been changed. However there seems to be a bug that this happens only once but not subsequent changes (this is reproducible). It can be triggered manually by using `redrawRows`. However this can clash with the execution of `redrawRows` that is automatically triggered resulting in an error. Trying to catch this error is helping sometimes, but the error still occurs. It seems to be a timing issue, so it is not always reproducible, but most of the time. It is required to update the color of a row or the comment/flags/acmg icons, i.e. it happens when putting a comment, flags or an acmg rating.

```javascript
try {
  this.gridApi.redrawRows({ rows: [this.gridRow] });
} catch (error) {}
```

**To Reproduce**
1. Open the vue.js implementation of the filter form.
2. Get variant results.
3. Open the variant details
4. Place a new comment where no comment has been before, assign flags where there haven't been flags, add and acmg rating wheter there wasn't one before.
5. See errors in the console and the table not responding anymore.

**Expected behavior**
Update the row color and flags/comment/acmg rating icons without hassle.

**Additional context**
Find a workaround and place this issue in the ag-grid helpdesk.

**Comment by holtgrewe** [comment]
Not relevant any more, as we don't use `ag-grid` any more.
