### ISSUE TITLE
Extend vue.js small variant filter form with remaining tabs

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-server#700]
**Is your feature request related to a problem? Please describe.**
The current vue.js implementation of the variant filter form is only done for frequency and genotype filter, all other settings are default. The data model exists, only the other forms need to be put into vue components and data-binded to the data model.

**Describe the solution you'd like**
All the form should be made available, including (quick) presets.

**Describe alternatives you've considered**
None.

**Comment by holtgrewe** [comment]
**Resolution Proposal**
Simply create one component per tab, more if necessary.

**Affected Components**
VarFish Server

**Affected Modules/Files**
`variants/vueapp`

**Required Architectural Changes**
None

**Required Database Changes**
None

**Backport Possible?**
No

**Resolution Sketch**
- [ ] Prioritization
- [ ] Variants & Effects
- [ ] Quality
- [ ] Clinvar, HGMD & dbSNP
- [ ] Gene Lists & Regions
- [ ] Flags & Comments
- [ ] Configure Downloads
- [ ] Miscellaneous
- [ ] Filter Import / Export

**Comment by holtgrewe** [comment]
Note: not porting over features from #739.
