### ISSUE TITLE
Remove old filter features

### ISSUE THREAD

**Issue by holtgrewe** [varfish-org/varfish-server#739]
**Is your feature request related to a problem? Please describe.**
There is a number of filter features that do not make sense any more.

**Describe the solution you'd like**
They should be removed:

- Require HGMD public membership (data too old to be useful)
- Remove dbSNP entries (too broad/dangerous)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by stolpeo** [comment]
related ticket: #779

**Comment by stolpeo** [comment]
- HGMD has a "pro" linkout setting in the config that currently is not used https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/config/settings/base.py#L563
- The HGMD database table is still joined and the accession number is used in a link out https://github.com/varfish-org/varfish-server/blob/6a308f5dfde372330f3880482b5e98a8948cd550/variants/vueapp/src/components/FilterResultsTable.vue#L704

@holtgrewe

**Comment by stolpeo** [comment]
I will remove HGMD database and link-outs that involve data from the HGMD table. If the data is outdated, the linkouts do not make sense. The HGMD Pro setting can be clarified later on.
