### ISSUE TITLE
Linkout to Genoox Franklin

### ISSUE THREAD

**Issue by your-highness** [varfish-org/varfish-server#748]
**Is your feature request related to a problem? Please describe.**
VarFish already provides many useful link outs. However, no link to the openly accessible Clincal DB of [Genoox Franklin](https://franklin.genoox.com) is included so far. 

**Describe the solution you'd like**
Similar to linkouts to UCSC, EnsEMBl _etc._ a link to Genoox Franklin should be included:
![image](https://user-images.githubusercontent.com/1949888/178541291-18bc4d01-9648-4672-a455-4f66040f6639.png)

The URL format follows this convention (needs to checked):
| Feature | URL | Comment |
| -------- | ----- | ----- |
| SNVs/InDels |  `https://franklin.genoox.com/clinical-db/variant/snp/chr11-17552955-C-CG` | Link to DB entry of a variant |
| CNV | `https://franklin.genoox.com/clinical-db/variant/sv/chr1-216138600-216270555-DEL` |  Shows a region viewer showing contained CNVs for DEL |

**Describe alternatives you've considered**
Using variante coordinates and manually check Genoox variant annotations via Copy&Paste.

**Additional context**
None.

**Comment by your-highness** [comment]
Dear @holtgrewe ,

I don't think PR #776 implements this feature. _Mixed up issue tags?_

**Comment by holtgrewe** [comment]
@your-highness I agree. Sorry.

**Comment by your-highness** [comment]
> @your-highness I agree. Sorry.

No problem. _Do you think this could be implemented and backported to athenea like #576?_

**Comment by your-highness** [comment]
@stolpeo : Thanks for the swift implementation and the backport to athenea. Very grateful!

**Comment by holtgrewe** [comment]
This does not work yet for the bollonaster branch and after the switch to the Vue.js frontend, it will need a fresh start. Re-opening this issue and closing old pull request.

**Comment by holtgrewe** [comment]
#1300
