### ISSUE TITLE
Filter Variants for Case: "In-House Variant Carriers" hangs

### ISSUE THREAD

**Issue by your-highness** [varfish-org/varfish-server#833]
**Describe the bug**
When looking up "In-House Variant Carriers" in "Filter Variants for Case/Results" takes 4 mins in a installation with 100 case installation. This action runs a PostgreSQL `SELECT` query with one thread but after 2 mins spawns a PostgreSQL `idle` state process. 

**To Reproduce**
1. Go to 'Filter Variants for Case/Results'
2. Click on '(Binoculars)' (opens pop up)
3. Wait 4 mins in a varfish-docker-compose installation with 100 cases
4. See 'In-House Variant Carriers"

**Expected behavior**
It's not really a bug that the computation takes some time but because it generates a popup "Filter Variants for Case/Results" further work in the variant details is blocked. _Would it be possible to show the result in a **new** tab/window?_

**Screenshots**
none needed

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox

**Additional context**
#470

**Comment by holtgrewe** [comment]
Feature removed for now in main branch, will be added back later.
