### ISSUE TITLE
in house pop frequency not displayed in join filtration mode

### ISSUE THREAD

**Issue by alexejknaus** [varfish-org/varfish-server#835]
**Describe the bug**
when using joint filtration of a cohort, then the in house population frequency in the filtered results is not shown.

**To Reproduce**
1. Go to 'cohort
2. select some cases and Click on 'create a cohort'
3. perform joint filtration of cohort
4. Scroll down to 'Results'
5. select for _frequency_ dropdown "in-house DB"
6. See error: no pop freq information is provided

![image](https://user-images.githubusercontent.com/37909805/215176007-52e93886-63b8-4390-a94e-fc36f3b6b2fe.png)

**Expected behavior**
hom and het pop freq should be visible
![image](https://user-images.githubusercontent.com/37909805/215175676-fac13cd1-070d-4948-8d4f-1b50e031558d.png)

**Comment by holtgrewe** [comment]
Joint filtration removed for now, will be added back later.
