### ISSUE TITLE
filter vue app result submission to mutation distiller

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-server#868]
**Is your feature request related to a problem? Please describe.**
The mutation distiller submission for the filter query results in the filter vue app is missing.

**Describe the solution you'd like**
Add the mutation distiller submission to the filter vue app for the filter query results.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by xiamaz** [comment]
Is this feature still used by anyone?
