### ISSUE TITLE
Scoring with MutationTaster broken

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-server#895]
**Describe the bug**
Apparently, MutationTaster changed its interface. Filtering with activated priorization with MutationTaster results in a broken results list.

**To Reproduce**
1. Go to filter page
2. Activate prioritization with MutationTaster
3. Filter
4. See empty list

**Expected behavior**
See results with MutationTaster score.

**Comment by xiamaz** [comment]
FYI at least for Medgen/CADS Scoring with MutationTaster is currently not used, as we only use CADD in our SOPs and routine filtering strategies and we should be fine with removing this feature until their API stabilizes.

**Comment by holtgrewe** [comment]
For now, scoring with MutationTaster has been removed.
