### ISSUE TITLE
DECIPHER gene based link out

### ISSUE THREAD

**Issue by alexejknaus** [varfish-org/varfish-server#962]
**Is your feature request related to a problem? Please describe.**
I would like to have a gene based link out to decipher
**Describe the solution you'd like**
when click on the gene drop down, I would like to see a link out to Decipher 
Gene example F13A1
![image](https://github.com/bihealth/varfish-server/assets/37909805/c8ad7e65-20f7-45a2-bb4f-80336cf68d2e)
ideally directly to _protein-genomic-info_

e.g.: https://www.deciphergenomics.org/gene/F13A1/overview/protein-genomic-info

**Comment by holtgrewe** [comment]
Subsumed by #1300.
