### ISSUE TITLE
Viewing comments of variants in other samples

### ISSUE THREAD

**Issue by alexejknaus** [varfish-org/varfish-server#964]
**Is your feature request related to a problem? Please describe.**
When adding a comment on a variant for a sample, I would like to see this comment for the same variant in another sample.

**Describe the solution you'd like**
Ideally in the table view it should be visible that a variant was already commented (or classified) by another user for another case. When opening the variant (left arrow), a list of all cases with that variant and the comments of that variant per case should be displayed in the comments and flags box.

**Additional context**
I am not sure whether this feature request will be obsolete in Bolonaster version.

**Comment by stolpeo** [comment]
We have another bug in here. The comments for a variant are not updated when switching from one case to another.

**Comment by stolpeo** [comment]
OK there is a fundamental problem of using `Promise.all([store1.initialize, store2.initialize, ...])` when initializing stores. Once the promise is resolved, recalling the function containing the promise doesn't open a new promise, instead it seems to be resolved, thus the stores in the promise.all do not update anymore.
